PREFIX :<http://www.ontotext.com/connectors/elasticsearch#>
PREFIX inst:<http://www.ontotext.com/connectors/elasticsearch/instance#>
INSERT DATA {
  inst:places :dropConnector [] .
};
INSERT DATA {
inst:places :createConnector '''
{
    "fields": [
        {
            "propertyChain": [
                "$self"
            ],
            "fieldName": "place_id",
            "multivalued": false,
            "ignoreInvalidValues": true
        },
        {
            "fieldName": "type",
            "propertyChain": [
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "typeLabel",
            "propertyChain": [
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
                "localName()"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "place_prefLabel",
            "propertyChain": [
                "http://www.geonames.org/ontology#name"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "analyzer": "keyword",
            "objectFields": []
        },
        {
            "fieldName": "place",
            "propertyChain": [
                "http://www.w3.org/2004/02/skos/core#altLabel"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "analyzer": "keyword",
            "objectFields": []
        },
        {
            "fieldName": "parent1_prefLabel",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentADM1",
                "http://www.geonames.org/ontology#name"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "analyzer": "keyword",
            "objectFields": []
        },
        {
            "fieldName": "parent1",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentADM1",
                "http://www.w3.org/2004/02/skos/core#altLabel"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "parent2_prefLabel",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentADM2",
                "http://www.geonames.org/ontology#name"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "parent2",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentADM2",
                "http://www.w3.org/2004/02/skos/core#altLabel"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "country_prefLabel",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentCountry",
                "http://www.geonames.org/ontology#name"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        },
        {
            "fieldName": "country",
            "propertyChain": [
                "http://www.geonames.org/ontology#parentCountry",
                "http://www.w3.org/2004/02/skos/core#altLabel"
            ],
            "indexed": true,
            "stored": true,
            "analyzed": true,
            "multivalued": true,
            "ignoreInvalidValues": false,
            "fielddata": false,
            "array": false,
            "objectFields": []
        }
    ],
    "languages": [],
    "types": [
        "http://www.geonames.org/ontology#Feature"
    ],
    "readonly": true,
    "detectFields": false,
    "importGraph": false,
    "elasticsearchNode": "http://elastic:9200",
    "elasticsearchClusterSniff": true,
    "manageIndex": true,
    "manageMapping": true,
    "bulkUpdateBatchSize": 5000,
    "bulkUpdateRequestSize": 5242880
}
''' .
}